/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as TeacherSubjectsRouteImport } from './routes/teacher.subjects'
import { Route as TeacherEarningsRouteImport } from './routes/teacher.earnings'
import { Route as TeacherDoubtsRouteImport } from './routes/teacher.doubts'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as StudentReferralsRouteImport } from './routes/student.referrals'
import { Route as StudentDoubtsRouteImport } from './routes/student.doubts'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters.$chapterId'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubjectsRoute = TeacherSubjectsRouteImport.update({
  id: '/teacher/subjects',
  path: '/teacher/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherEarningsRoute = TeacherEarningsRouteImport.update({
  id: '/teacher/earnings',
  path: '/teacher/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDoubtsRoute = TeacherDoubtsRouteImport.update({
  id: '/teacher/doubts',
  path: '/teacher/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReferralsRoute = StudentReferralsRouteImport.update({
  id: '/student/referrals',
  path: '/student/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDoubtsRoute = StudentDoubtsRouteImport.update({
  id: '/student/doubts',
  path: '/student/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/admin/referrals',
  path: '/admin/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/doubts': typeof StudentDoubtsRoute
  '/student/referrals': typeof StudentReferralsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/teacher/doubts': typeof TeacherDoubtsRoute
  '/teacher/earnings': typeof TeacherEarningsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/doubts': typeof StudentDoubtsRoute
  '/student/referrals': typeof StudentReferralsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/teacher/doubts': typeof TeacherDoubtsRoute
  '/teacher/earnings': typeof TeacherEarningsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/tests': typeof TestsIndexRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/doubts': typeof StudentDoubtsRoute
  '/student/referrals': typeof StudentReferralsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/teacher/doubts': typeof TeacherDoubtsRoute
  '/teacher/earnings': typeof TeacherEarningsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/courses'
    | '/admin/referrals'
    | '/admin/teachers'
    | '/admin/withdrawals'
    | '/chapters/$chapterId'
    | '/student/courses'
    | '/student/doubts'
    | '/student/referrals'
    | '/subjects/$subjectId'
    | '/teacher/doubts'
    | '/teacher/earnings'
    | '/teacher/subjects'
    | '/tests/$testId'
    | '/topics/$topicId'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/teacher/'
    | '/tests/'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/courses'
    | '/admin/referrals'
    | '/admin/teachers'
    | '/admin/withdrawals'
    | '/chapters/$chapterId'
    | '/student/courses'
    | '/student/doubts'
    | '/student/referrals'
    | '/subjects/$subjectId'
    | '/teacher/doubts'
    | '/teacher/earnings'
    | '/teacher/subjects'
    | '/tests/$testId'
    | '/topics/$topicId'
    | '/admin'
    | '/courses'
    | '/student'
    | '/teacher'
    | '/tests'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/courses'
    | '/admin/referrals'
    | '/admin/teachers'
    | '/admin/withdrawals'
    | '/chapters/$chapterId'
    | '/student/courses'
    | '/student/doubts'
    | '/student/referrals'
    | '/subjects/$subjectId'
    | '/teacher/doubts'
    | '/teacher/earnings'
    | '/teacher/subjects'
    | '/tests/$testId'
    | '/topics/$topicId'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/teacher/'
    | '/tests/'
    | '/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDoubtsRoute: typeof StudentDoubtsRoute
  StudentReferralsRoute: typeof StudentReferralsRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  TeacherDoubtsRoute: typeof TeacherDoubtsRoute
  TeacherEarningsRoute: typeof TeacherEarningsRoute
  TeacherSubjectsRoute: typeof TeacherSubjectsRoute
  TestsTestIdRoute: typeof TestsTestIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/subjects': {
      id: '/teacher/subjects'
      path: '/teacher/subjects'
      fullPath: '/teacher/subjects'
      preLoaderRoute: typeof TeacherSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/earnings': {
      id: '/teacher/earnings'
      path: '/teacher/earnings'
      fullPath: '/teacher/earnings'
      preLoaderRoute: typeof TeacherEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/doubts': {
      id: '/teacher/doubts'
      path: '/teacher/doubts'
      fullPath: '/teacher/doubts'
      preLoaderRoute: typeof TeacherDoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/referrals': {
      id: '/student/referrals'
      path: '/student/referrals'
      fullPath: '/student/referrals'
      preLoaderRoute: typeof StudentReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/doubts': {
      id: '/student/doubts'
      path: '/student/doubts'
      fullPath: '/student/doubts'
      preLoaderRoute: typeof StudentDoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDoubtsRoute: StudentDoubtsRoute,
  StudentReferralsRoute: StudentReferralsRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  TeacherDoubtsRoute: TeacherDoubtsRoute,
  TeacherEarningsRoute: TeacherEarningsRoute,
  TeacherSubjectsRoute: TeacherSubjectsRoute,
  TestsTestIdRoute: TestsTestIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
